# General
title: Пишу о разработке
author: Dmitry Surin
email: dmitry.surin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Интересное в мире разработки. Чистый код, архитектура, разработка и тестирование.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://surin.blog" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:title/
encoding: utf-8
show_excerpts: true
excerpt_separator: <!--more-->

menu:
  - name: Блог
    url: /
  - name: Переводы
    url: /translations/
  - name: Обо мне
    url: /about/

# Links
twitter_username: BedwaRe
github_username: bedware
stackoverflow_id: 8413677

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Plugins
google_analytics: UA-134200140-1
disqus_shortname: bedware

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - package.json
  - package-lock.json
  - gulpfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
