# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Пишу о разработке
author: Дмитрий Сурин
email: dmitry.surin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Интересное в мире разработки. Чистый код, архитектура, разработка и тестирование.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: :year/:month/:day/:title.html
encoding: utf-8
date_format: "%d-%m-%Y"

# Links
twitter_username: BedwaRe
github_username: bedware
show_excerpts: true

menu:
  - name: Блог
    url: /
  - name: Переводы
    url: /translations/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Plugins
#google_analytics: UA-NNNNNNNN-N
disqus:
  shortname: bedware

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - package.json
  - package-lock.json
  - gulpfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
